[colors]
[colors.primary]
background = '{{background}}'
foreground = '{{foreground}}'

# Normal colors
[colors.normal]
black = '{{normal_black}}'
red = '{{normal_red}}'
green = '{{normal_green}}'
yellow = '{{normal_yellow}}'
blue = '{{normal_blue}}'
magenta = '{{normal_magenta}}'
cyan = '{{normal_cyan}}'
white = '{{normal_white}}'

# Bright colors
[colors.bright]
black = '{{bright_black}}'
red = '{{bright_red}}'
green = '{{bright_green}}'
yellow = '{{bright_yellow}}'
blue = '{{bright_blue}}'
magenta = '{{bright_magenta}}'
cyan = '{{bright_cyan}}'
white = '{{bright_white}}'

[colors.selection]
background = '{{selection_background}}'
