alacritty:
  background: color_3
  foreground: color_22
  normal_black: color_8
  normal_red: color_32
  normal_green: color_21
  normal_yellow: color_31
  normal_blue: color_18
  normal_magenta: color_24
  normal_cyan: color_13
  normal_white: color_17
  bright_black: color_12
  bright_red: color_33
  bright_green: color_25
  bright_yellow: color_34
  bright_blue: color_19
  bright_magenta: color_26
  bright_cyan: color_0
  bright_white: color_23
  selection_background: color_18
btop:
  main_bg: color_3
  main_fg: color_22
  title: color_18
  hi_fg: color_26
  selected_bg: color_7
  selected_fg: color_27
  graph_text: color_15
  meter_bg: color_10
  proc_misc: color_31
  cpu_box: color_18
  mem_box: color_21
  net_box: color_20
  proc_box: color_32
  div_line: color_11
  graph_line: color_15
  cpu_start: color_21
  cpu_mid: color_31
  cpu_end: color_32
  mem_start: color_21
  mem_mid: color_31
  mem_end: color_32
  net_rx: color_20
  net_tx: color_26
  proc_start: color_18
  proc_mid: color_21
  proc_end: color_31
chromium:
  frame: color_3
  frame_inactive: color_2
  toolbar: color_4
  tab_text: color_27
  bookmark_text: color_22
  ntp_background: color_3
  ntp_text: color_22
  button_background: color_18
  button_foreground: color_3
  highlight: color_26
  highlight_text: color_3
eza:
  user: color_22
  group: color_21
  permission_read: color_18
  permission_write: color_31
  permission_exec: color_32
  directory: color_18
  file: color_27
  symlink: color_26
  pipe: color_31
  socket: color_21
  block_device: color_34
  char_device: color_0
  git_new: color_21
  git_modified: color_31
  git_deleted: color_32
  git_untracked: color_15
  special: color_20
hyprland:
  border_color_1: 33ccffee
  border_color_2: 00ff99ee
  border_angle: 45deg
hyprlock:
  color: 26,27,38,1.0
  inner_color: 26,27,38,0.8
  outer_color: 205,214,244,1.0
  font_color: 205,214,244,1.0
  check_color: 68,157,171,1.0
kitty:
  theme_name: tokyonight
  author: Folke Lemaitre
  upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_night.conf
  background: color_3
  foreground: color_27
  selection_background: color_5
  selection_foreground: color_27
  url_color: color_16
  cursor: color_27
  cursor_text_color: color_3
  active_tab_background: color_18
  active_tab_foreground: color_2
  inactive_tab_background: color_6
  inactive_tab_foreground: color_14
  active_border_color: color_18
  inactive_border_color: color_6
  color0: color_1
  color1: color_32
  color2: color_21
  color3: color_31
  color4: color_18
  color5: color_26
  color6: color_20
  color7: color_22
  color8: color_11
  color9: color_32
  color10: color_21
  color11: color_31
  color12: color_18
  color13: color_26
  color14: color_20
  color15: color_27
  color16: color_34
  color17: color_30
mako:
  include_path: ~/.local/share/omarchy/default/mako/core.ini
  text_color: color_22
  border_color: color_9
  background_color: color_3
  padding: 10
  border_size: 2
  font: Liberation Sans 11
  max_icon_size: 32
  outer_margin: 20
swayosd:
  background_color: color_3
  border_color: color_9
  label: color_22
  image: color_22
  progress: color_22
walker:
  selected_text: color_20
  text: color_29
  base: color_3
  border: color_9
  foreground: color_29
  background: color_3
waybar:
  foreground: color_28
  background: color_3
