alacritty:
  background: '#1a1b26'
  foreground: '#a9b1d6'
  normal_black: '#32344a'
  normal_red: '#f7768e'
  normal_green: '#9ece6a'
  normal_yellow: '#e0af68'
  normal_blue: '#7aa2f7'
  normal_magenta: '#ad8ee6'
  normal_cyan: '#449dab'
  normal_white: '#787c99'
  bright_black: '#444b6a'
  bright_red: '#ff7a93'
  bright_green: '#b9f27c'
  bright_yellow: '#ff9e64'
  bright_blue: '#7da6ff'
  bright_magenta: '#bb9af7'
  bright_cyan: '#0db9d7'
  bright_white: '#acb0d0'
  selection_background: '#7aa2f7'

btop:
  main_bg: '#1a1b26'
  main_fg: '#a9b1d6'
  title: '#7aa2f7'
  hi_fg: '#bb9af7'
  selected_bg: '#2e3248'
  selected_fg: '#c0caf5'
  graph_text: '#565f89'
  meter_bg: '#3b4261'
  proc_misc: '#e0af68'
  cpu_box: '#7aa2f7'
  mem_box: '#9ece6a'
  net_box: '#7dcfff'
  proc_box: '#f7768e'
  div_line: '#414868'
  graph_line: '#565f89'
  cpu_start: '#9ece6a'
  cpu_mid: '#e0af68'
  cpu_end: '#f7768e'
  mem_start: '#9ece6a'
  mem_mid: '#e0af68'
  mem_end: '#f7768e'
  net_rx: '#7dcfff'
  net_tx: '#bb9af7'
  proc_start: '#7aa2f7'
  proc_mid: '#9ece6a'
  proc_end: '#e0af68'

chromium:
  frame: '#1a1b26'
  frame_inactive: '#16161e'
  toolbar: '#1f2335'
  tab_text: '#c0caf5'
  bookmark_text: '#a9b1d6'
  ntp_background: '#1a1b26'
  ntp_text: '#a9b1d6'
  button_background: '#7aa2f7'
  button_foreground: '#1a1b26'
  highlight: '#bb9af7'
  highlight_text: '#1a1b26'

eza:
  user: '#a9b1d6'
  group: '#9ece6a'
  permission_read: '#7aa2f7'
  permission_write: '#e0af68'
  permission_exec: '#f7768e'
  directory: '#7aa2f7'
  file: '#c0caf5'
  symlink: '#bb9af7'
  pipe: '#e0af68'
  socket: '#9ece6a'
  block_device: '#ff9e64'
  char_device: '#0db9d7'
  git_new: '#9ece6a'
  git_modified: '#e0af68'
  git_deleted: '#f7768e'
  git_untracked: '#565f89'
  special: '#7dcfff'

hyprland:
  border_color_1: '33ccffee'
  border_color_2: '00ff99ee'
  border_angle: '45deg'

hyprlock:
  color: '26,27,38,1.0'
  inner_color: '26,27,38,0.8'
  outer_color: '205,214,244,1.0'
  font_color: '205,214,244,1.0'
  check_color: '68,157,171,1.0'

kitty:
  theme_name: 'Tokyo Night'
  author: 'Folke Lemaitre'
  upstream: 'https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_night.conf'
  background: '#1a1b26'
  foreground: '#c0caf5'
  selection_background: '#283457'
  selection_foreground: '#c0caf5'
  url_color: '#73daca'
  cursor: '#c0caf5'
  cursor_text_color: '#1a1b26'
  active_tab_background: '#7aa2f7'
  active_tab_foreground: '#16161e'
  inactive_tab_background: '#292e42'
  inactive_tab_foreground: '#545c7e'
  active_border_color: '#7aa2f7'
  inactive_border_color: '#292e42'
  color0: '#15161e'
  color1: '#f7768e'
  color2: '#9ece6a'
  color3: '#e0af68'
  color4: '#7aa2f7'
  color5: '#bb9af7'
  color6: '#7dcfff'
  color7: '#a9b1d6'
  color8: '#414868'
  color9: '#f7768e'
  color10: '#9ece6a'
  color11: '#e0af68'
  color12: '#7aa2f7'
  color13: '#bb9af7'
  color14: '#7dcfff'
  color15: '#c0caf5'
  color16: '#ff9e64'
  color17: '#db4b4b'

mako:
  include_path: '~/.local/share/omarchy/default/mako/core.ini'
  text_color: '#a9b1d6'
  border_color: '#33ccff'
  background_color: '#1a1b26'
  padding: 10
  border_size: 2
  font: 'Liberation Sans 11'
  max_icon_size: 32
  outer_margin: 20

swayosd:
  background_color: '#1a1b26'
  border_color: '#33ccff'
  label: '#a9b1d6'
  image: '#a9b1d6'
  progress: '#a9b1d6'

walker:
  selected_text: '#7dcfff'
  text: '#cfc9c2'
  base: '#1a1b26'
  border: '#33ccff'
  foreground: '#cfc9c2'
  background: '#1a1b26'

waybar:
  foreground: '#cdd6f4'
  background: '#1a1b26'
